# -*- coding: utf-8 -*-
"""ELT com python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTiojXTTOXlSyMNDOEi9FIyqcad3EmaP
"""

import requests
import pandas as pd
from sqlalchemy import create_engine

def extract()-> dict:
    API_URL = "http://universities.hipolabs.com/search?country=Brazil"
    data = requests.get(API_URL).json()
    return data

data = extract()

def transform(data:dict) -> pd.DataFrame:
    df = pd.DataFrame(data)
    print(f"Número total de univercidades do API {len(data)}")
    df = df[df["name"].str.contains("Goiás")]
    print(f"Número de universidades em Goiás {len(df)}")
    df['domains'] = [','.join(map(str, l)) for l in df['domains']]
    df['web_pages'] = [','.join(map(str, l)) for l in df['web_pages']]
    df = df.reset_index(drop=True)
    return df[["domains", "country", "web_pages","name"]]

def load(df:pd.DataFrame) -> None:
    disk_engine = create_engine('sqlite:///my_lite_store.db')
    df.to_sql('goias_uni', disk_engine, if_exists='replace')

import os

if os.path.exists('my_lite_store.db'):
    os.remove('my_lite_store.db')

data = extract()
df = transform(data)
load(df)

import sqlite3
import pandas as pd

conn = sqlite3.connect('my_lite_store.db')
query = "SELECT * FROM goias_uni"
df_from_db = pd.read_sql_query(query, conn)
display(df_from_db)
conn.close()